# Generated by Django 5.2.8 on 2025-12-30 11:07

import datetime
import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(blank=True, default=events.models.current_time, null=True)),
                ('location', models.CharField(max_length=300)),
                ('event_image', models.ImageField(blank=True, default='events_image/defout_img.png', null=True, upload_to='events_image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.category')),
            ],
        ),
    ]
