# Generated by Django 6.0 on 2025-12-12 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(14, 6, 15, 72808), null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='participants', to='events.event'),
        ),
    ]
