# Generated by Django 6.0 on 2025-12-12 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_time_alter_participant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(14, 7, 58, 218203), null=True),
        ),
    ]
