# Generated by Django 5.2.8 on 2025-12-23 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_participants_alter_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default='static/images/banner.jpg', null=True, upload_to='events_image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(6, 6, 47, 517628), null=True),
        ),
    ]
