# Generated by Django 5.2.8 on 2025-12-23 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_event_image_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default='events_image/defout_img.png', null=True, upload_to='events_image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(6, 23, 17, 383416), null=True),
        ),
    ]
