# Generated by Django 5.2.8 on 2025-12-24 14:35

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=events.models.current_time, null=True),
        ),
    ]
